#!/usr/bin/env bash
# Install and configure HAProxy to load balance between web-01 and web-02

# Update packages
sudo apt-get update -y

# Install HAProxy
sudo apt-get install -y haproxy

# Enable HAProxy on boot
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend web_servers

backend web_servers
    balance roundrobin
    server web-01 54.234.11.134:80 check
    server web-02 13.221.79.8:80 check
EOF

# Restart HAProxy
sudo service haproxy restart
