#!/usr/bin/env bash
# Configures a new Ubuntu machine with Nginx and a page containing Holberton School

sudo apt-get update -y
sudo apt-get install -y nginx
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx restart
